### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto-golang#106]
*Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.*

People at Kubecon 2021 mentioned that they want  a CLI tool for in-toto-golang. There is a cli tool for testing in one of our forks. We should adopt it.

**Description of issue or feature request**:

Provide a cli tool via a separate cmd directory.

**Current behavior**:

This repository just provides a library.

**Expected behavior**:

This library should also provide a cli tool with basic functionality.

**Comment by adityasaky** [comment]
Curious, are they using in-toto-golang already and therefore don't want to install in-toto-python because it's redundant?

I believe the CLI you're referring to is: https://github.com/boxboat/in-toto-golang/tree/master/in_toto/cmd

**Comment by shibumi** [comment]
@adityasaky  yes, I am referring to this CLI. As far as I know the CLI was just there for easier testing and I really like the idea of having a CLI for integration tests and so on. I think with a CLI we could much easier test if the go library produces the same result like the in-toto cli.

**Comment by adityasaky** [comment]
Closed by #56.
