### ISSUE TITLE
Potential bug in InTotoRun

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto-golang#124]
**Description of issue or feature request**:

https://github.com/in-toto/in-toto-golang/blob/02b98c8d4e2220c5fa5b992f39cd167986cede78/in_toto/runlib.go#L293 

We are not handling an empty `cmdArgs` either as `nil` or empty string slice. We should check if our code still works with both and that we are not running into a panic.

Furthermore, we should add tests to cover these edge cases.

**Comment by adityasaky** [comment]
Closed by #126.
