### ISSUE TITLE
in_toto.Signature struct definition does not match specification

### ISSUE THREAD

**Issue by nmiyake** [in-toto/in-toto-golang#130]
The current definition of `in_toto.Signature` in this library is as follows https://github.com/in-toto/in-toto-golang/blob/master/in_toto/model.go#L306:

```
type Signature struct {
	KeyID       string `json:"keyid"`
	Sig         string `json:"sig"`
	Certificate string `json:"cert"`
}
```

This definition contains a "cert" field. However, this field is not part of the in-toto specification: per https://github.com/in-toto/docs/blob/master/in-toto-spec.md#42-file-formats-general-principles, items in the "signatures" block should only have "keyid" and "sig".

The "cert" field is also not part of the Python schema (https://github.com/secure-systems-lab/securesystemslib/blob/master/securesystemslib/formats.py#L397) and none of the example files I have seen contain it either (for example, https://github.com/in-toto/kubectl-in-toto/blob/master/example/functionary/build.f5c8b97a.link#L3).

The current behavior causes issues when marshalling an `in_toto.Metablock` struct as JSON because the extra field is included:

```
{
  "signatures": [
    {
      "cert": "",
      "keyid": "706bdfbb46c397eb55a64c902c5241dabeb16cfa5c7456250800441bade2cdf9",
      "sig": "827074c151970a7e45cbc5b8d66ba84b9e501e699a826d37132853fac889e58e542b6f860c3399e157bab7afdad9bee24523e2ac40427c4c93e821d2c936a260329fd2262b78ef431fd06014b9a7c154282fc3f37f9e7ac18c015350dd6da6ea3ae7bfd43615d8dec3d9f18ce389aa8598253bc84c71646956e34c887a0424e5af89ffe395018cf71470121ae657d9129c4b6edc3f75edab45c1ee78f9c662234d148e3aa972a5cbbca46f1c7c18fd8c4fc6a54e3338a0b318cc21d0f6634279f18187367fb457789eaa7df30a420eab98d9e682e41821e82daed015f92699605f0a60f45496b3497e23a553bcc11fe1d00ed64c42ce15dd02ce5f10df8bb9cb"
    }
  ],
```

Given that "cert" is not part of the spec, it seems like it should not be part of this struct either (or, at minimum, the JSON field should be annotated with `omitempty` like https://github.com/in-toto/in-toto-golang/blob/master/in_toto/model.go#L30 so that it is not written out when a value is not present).

**Comment by adityasaky** [comment]
Hi, @nmiyake, thanks for the report! This field is indeed new, the PR was merged just a couple of weeks ago, and you're right that it likely needs an `omitempty`. As for documenting the field, it's currently under discussion as an in-toto Enhancement (ITE) that adds certificate support to in-toto. You can find that here: https://github.com/in-toto/ITE/pull/21. In the meantime, an `omitempty` should and will be added to the field, stay tuned.

**Comment by adityasaky** [comment]
Just added `omitempty` via #132, @nmiyake. I'm going to go ahead and close this. Are you currently using v0.3.0?

**Comment by adityasaky** [comment]
https://github.com/in-toto/in-toto-golang/releases/tag/v0.3.1

Just released this with a fix. Hopefully that solves the problem for you. :)

**Comment by nmiyake** [comment]
@adityasaky thanks for the quick turnaround! I had worked around it by defining an equivalent struct without the extra data structure and copying into and marshalling that struct, but have verified that this update allows me to get rid of that extra logic. Appreciate the extra context on the discussion around the enhancement as well. This is now fully resolved on my end.
