### ISSUE TITLE
Add version/SHA to provevanceBuilder

### ISSUE THREAD

**Issue by laurentsimon** [in-toto/in-toto-golang#159]
The provenance builder contains only an ID field, see https://github.com/in-toto/in-toto-golang/blob/master/in_toto/slsa_provenance/v0.2/provenance.go#L22)](https://github.com/in-toto/in-toto-golang/blob/master/in_toto/slsa_provenance/v0.2/provenance.go#L22

It would be beneficial to add a Version and a Digest field, because the builder itself needs to be identified uniquely.

An alternative would be to use ID=`theID:version@hash`. I don't think this is a good approach because it treats the builder differently from the rest of he provenance information (ConfigSource contains a digest, for example) 

One may ask why we need a version if we have a hash. Versions are useful during verification of the provenance: based on a the version, the verifier can adjust its logic/verification. Hashes don't allow to do this easily.

Maybe I'm misunderstanding the purpose of provenanceBuilder, and the intention may be to put the data I'm after inside `ConfigSource`? (which does not contain a version field either).

Note: my use case is a build using a GitHub action on GitHub. The builder is the action (which has a version and a hash). 

cc @asraa

**Comment by laurentsimon** [comment]
cc @MarkLodato @TomHennen

**Comment by MarkLodato** [comment]
This is actually a question for the https://slsa.dev/provenance/v0.2 spec, not necessarily the in-toto-golang implementation. In other words, this about adding new `builder.digest` and `builder.version` fields to the schema. So I'll move the bug there. See https://github.com/slsa-framework/slsa/issues/319.

**Comment by adityasaky** [comment]
Closing this in favour of https://github.com/slsa-framework/slsa/issues/319.
