### ISSUE TITLE
Support older SLSA version and v1.0

### ISSUE THREAD

**Issue by chuangw6** [in-toto/in-toto-golang#176]
In today's [in-toto community meeting](https://hackmd.io/@lukpueh/ry_e70Qqw#07012022-Meeting) (2022-07-01), we discussed that we want to have namespaced implemetation for the statement struct with [SLSA v1](https://github.com/slsa-framework/slsa-proposals/blob/main/0002/README.md) predicate when it comes out in next couple of months. This way, we can maintain the current [slsav0.2-specific statement struct](https://github.com/in-toto/in-toto-golang/blob/b4a6b184fd3ad4658e5018bc58e5f5a89fb23da5/in_toto/model.go#L986-L990) to allow a deprecation window.

(https://github.com/in-toto/attestation/issues/98 tracks all predicate types for the intoto statement)

If you have any questions or comments, feel free to add them here.

**Comment by chuangw6** [comment]
cc @adityasaky @SantiagoTorres @joshuagl @mlieberman85

**Comment by adityasaky** [comment]
Adding explicit models for v0.1 and v0.2 right now should be a minor diff, and will probably help us evaluate the work that goes into keeping multiple provenance versions around. Do you think you can open a PR to support v0.1 @chuangw6?

**Comment by mlieberman85** [comment]
In the same vein does also make sense to separate out specific in-toto golang predicates that are supported to its own library? I don't want to conflate the two issues but I wonder if we might run into issues where we want to have a separate release cadence for in-toto-golang itself from community supported in-toto predicates.

**Comment by chuangw6** [comment]
> Adding explicit models for v0.1 and v0.2 right now should be a minor diff, and will probably help us evaluate the work that goes into keeping multiple provenance versions around. Do you think you can open a PR to support v0.1 @chuangw6?

sgtm! Added #177 Please take a took.

**Comment by chuangw6** [comment]
Hi @mlieberman85 ,
sorry for the delay.

> In the same vein does also make sense to separate out specific in-toto golang predicates that are supported to its own library? 

Do you mean each slsa version has its own repository in the `in-toto` project? 

> I don't want to conflate the two issues but I wonder if we might run into issues where we want to have a separate release cadence for in-toto-golang itself from community supported in-toto predicates.

Can you please explain a bit or provide a bit more context? 
Thank you!

**Comment by adityasaky** [comment]
> I don't want to conflate the two issues but I wonder if we might run into issues where we want to have a separate release cadence for in-toto-golang itself from community supported in-toto predicates.

I can see this becoming an issue and I think we can explore a separate in-toto/predicates library once we have >1 predicate implementations perhaps?

**Comment by mlieberman85** [comment]
> Hi @mlieberman85 , sorry for the delay.
> 
> > In the same vein does also make sense to separate out specific in-toto golang predicates that are supported to its own library?
> 
> Do you mean each slsa version has its own repository in the `in-toto` project?
> 
> > I don't want to conflate the two issues but I wonder if we might run into issues where we want to have a separate release cadence for in-toto-golang itself from community supported in-toto predicates.
> 
> Can you please explain a bit or provide a bit more context? Thank you!

Sorry, @chuangw6 I missed this. As @adityasaky mentioned, it might make sense once we end up with multiple predicates to split it into a library. Probably don't need to have individual repos for each predicate but it just helps us separate out the predicates themselves from the in-toto implementation itself.

**Comment by adityasaky** [comment]
I think it's reasonable to close this now considering #177 has been merged and we have a plan for how to handle future SLSA versions.
