### ISSUE TITLE
CycloneDX predicate is wrong

### ISSUE THREAD

**Issue by lehors** [in-toto/in-toto-golang#187]
**General information:**

CycloneDX support was added in PR #169 by defining a predicate for it but its value is wrong.

**Description of the bug:**

The CycloneDX predicate is currently defined as "https://cyclonedx.org/schema" but the CycloneDX project has decided to use "https://cyclonedx.org/bom" instead. The latter is already used by some tools like syft and the discrepancy is creating incompatibilities with tools like cosign that are using the definition from this package.

**Anything special you want to tell us?**

For more info on this see: https://github.com/in-toto/attestation/issues/82#issuecomment-1280759933 and
https://github.com/in-toto/attestation/issues/82#issuecomment-1280983953

**Comment by shibumi** [comment]
Fixed with: https://github.com/in-toto/in-toto-golang/pull/188#event-7614433625
