### ISSUE TITLE
in-toto-golang record stop doesn't removes unfinished link.

### ISSUE THREAD

**Issue by PradyumnaKrishna** [in-toto/in-toto-golang#244]
**Description of the bug:**
If we use `in-toto-golang record start` it generates an unfinished link, when we stop record using `in-toto-golang record stop` command it doesn't removed that unfinished link. This is a minor difference between the in-toto python and go implementations.

**Anything special you want to tell us?**
in-toto python implemenation removes that unfinished link.
https://github.com/in-toto/in-toto/blob/2b9b07ca7c803f5043bdd46d0c403c666e0c3b41/in_toto/runlib.py#L1056

**Comment by adityasaky** [comment]
Good eye! I think it should be patched at the CLI (https://github.com/in-toto/in-toto-golang/blob/master/cmd/record.go#L190) since the API accepts a `Metadata` instance and is disconnected from the filesystem.

**Comment by PradyumnaKrishna** [comment]
I will create a fix for this.
