### ISSUE TITLE
Oversight in the SLAS v1 field `invocationID`?

### ISSUE THREAD

**Issue by chuangw6** [in-toto/in-toto-golang#260]
**Description of the bug:**

In the SLSA v1 provenance, the json tag for the field invocation id should be `invocationId` instead of `invocationID` per [slsa v1 spec](https://slsa.dev/spec/v1.0/provenance#schema) on the official website and [the proto](https://github.com/in-toto/attestation/blob/main/protos/in_toto_attestation/predicates/provenance/v1/provenance.proto).

But the tag in in-toto-golang is `invocationID` https://github.com/in-toto/in-toto-golang/blob/5fd5c6748041bbaf5fd05da2a16dcb2c96dc30b6/in_toto/slsa_provenance/v1/provenance.go#L144

**Comment by chuangw6** [comment]
cc @adityasaky

**Comment by adityasaky** [comment]
I think it's preferable to fix this by directly using the proto. I know @marcelamelara was interested in getting this done too, unfortunately I've been a little swamped. @marcelamelara do you have any cycles to help out here?

**Comment by chuangw6** [comment]
> I think it's preferable to fix this by directly using the proto.

Agreed.

**Comment by marcelamelara** [comment]
+1 to switching to using the protobufs in this implementation. IIRC, the last time I looked at making this change happen, it wasn't quite as simple as replacing one struct for the other, but I'll have _some_ cycles in the next week or two, so I can take a look.

**Comment by msuozzo** [comment]
The aforementioned change is still not submitted so the proto version is effectively unusable. Can we merge the fix for this issue in the meantime? https://github.com/in-toto/in-toto-golang/pull/328

**Comment by msuozzo** [comment]
Is this worth a patch-release? This is technically a bug fix but I can pin to the commit hash if necessary.

**Comment by adityasaky** [comment]
I'll try and tag a release tomorrow. There are a couple pending updates etc we should probably merge as well, I'll check if someone has a few to take a pass at fixing some of the CI issues!
