### ISSUE TITLE
Support multiple hashing algorithms

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto-golang#31]
**Description of issue or feature request**: The current implementation is fixed to sha256. While this is is enough for a MVP, we need to support plug-able and extendable hash functions.

**Current behavior**: It is not possible to generate hashes using any other algorithm than sha256.

**Expected behavior**: It should be possible to programmatically select the hashing algorithm to compute artifact integrity and for signature verification.

**Comment by hisenberg08** [comment]
I have added a couple of more hash functions in the code but it is still a static list of hash algorithms. 
Also the hash functions I am using are the one provided by the crypto library in go.
Is it okay if I keep using the same library?
How exactly do we need to make it plug-able ?
One option could be to read the list of hash functions from a configuration file.

**Comment by SantiagoTorres** [comment]
Hi, @hisenberg08!

 This does seem reasonable,

What I'd like to have is an adapter in which we can easily add support for more hash algos if needed. Why don't you share what we have and we start discussing a path forward?

**Comment by lukpueh** [comment]
Thanks for working on this, @hisenberg08! 

You might want to take a look at the various `create.*signature` and `verify.*signature` functions in [`securesystemslib`](https://github.com/secure-systems-lab/securesystemslib) (i.e. the crypto library we use for our Python reference implementation).

Most of those functions have some sort of *signature scheme* parameter, which encodes the hashing algorithm used to create or verify a signature. IIRC they currently all support only one scheme, but to prepare the same sort of extensibility is what we want here in the golang implementation.
Same goes for hashing algorithms used to generate a keyid (see `securesystemslib.keys._get_keyid`).

Both signature `scheme` and `keyid_hash_algorithms` should be defined directly on the corresponding key (see the various schema definitions in `securesystemslib.formats`).

And there is one more place where we want to support the use of different hashing algorithms, that is when we record *materials* and *products* (see [`in_toto.runlib._hash_artifact`](https://github.com/in-toto/in-toto/blob/develop/in_toto/runlib.py#L54)).

Please reach out if you have any further questions!

**Comment by SantiagoTorres** [comment]
partly fixed by #39 . A CLI/API change is needed to allow for these algorithms to be completely pluggable.
