### ISSUE TITLE
Exclude patterns

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto-golang#33]
**Description of issue or feature request**: The python implementation has a nice frontend feature to ignore artifacts a-la `.gitignore` we should port that.

**Current behavior**: This feature is not implemented, so runlib captures all the materials in the directory.

**Expected behavior**: It should be possible to specify patterns to ignore when collecting file integrity.

**Comment by ayush159** [comment]
I have started working on this issue. I had a question regarding this:

In the python implementation, pathspec package is used. I have found a similar implementation of gitignore for GO here -> https://github.com/xanzy/go-pathspec . Can we use this package? 

I have pushed a partially working fix of this issue on my branch (https://github.com/ayush159/in-toto-golang/tree/master/in_toto) using this package.

**Comment by SantiagoTorres** [comment]
Hi @ayush159 !

I think it's fine if you want to include pathspec into the implementation, although I may want to take a look at this pkg more closely to make sure the license and everything doesn't clash with what we're doing. What do you think @lukpueh?

I'm looking at your fix, and it looks like it's going in the right direction, but you may want to simplify the code a little bit (those big if/else blocks could probably be replaced with guard statements and whatnot).

**Comment by lukpueh** [comment]
License compatibility seems fine. What worries me more is the low repo activity (most recent commit in 2014). Not sure if that's a problem though. Have you looked for alternatives? What about the 
[`gitignore`](https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/format/gitignore) subpackage from [`go-git`](https://github.com/src-d/go-git)?

**Comment by lukpueh** [comment]
I think this feature was fully implemented with #51. But before we close here, let's also remove the corresponding [todo item from the repo README](https://github.com/in-toto/in-toto-golang/blame/f3f615b900aa4798e9f0558f2f90c37884d0345f/README.md#L31)
