### ISSUE TITLE
Allow passing directory for inspections

### ISSUE THREAD

**Issue by radu-matei** [in-toto/in-toto-golang#46]
Currently, you cannot run the inspections when the materials and products are in a different directory than the current directory. 

https://github.com/in-toto/in-toto-golang/blob/b2f1d5db81b09e5daab2f20976d9538c1604ccdc/in_toto/verifylib.go#L39

This means that while you can pass the paths for the layout and root key, you have to be in the same directory with the rest of the materials to execute the verification with this library, or copy around the materials.

Given the fact that most commonly, the in-toto artifacts are usually grouped in the same directory, would it make sense to be able to pass the path?

[This branch](https://github.com/in-toto/in-toto-golang/compare/master...radu-matei:inspections-dir) introduces that path to the `RunInspections` functions, but does not break compatibility for the `InTotoVerify` function by creating a new one, `InTotoVerifyWithDirectory`.

Of course, the implementation is open for discussion, but is the functionality something desired in the library?

Thanks!

**Comment by lukpueh** [comment]
Thanks for the request, @radu-matei!  We have discussed this feature on the Python reference implementation repo a while ago (see in-toto/in-toto#258). 

Back then we concluded that it is reasonable to ask the verifier to copy and change to a temporary directory. This is what the folks at datadog, who had asked for this feature, ended up doing (see https://github.com/DataDog/integrations-core/pull/3282). Would that work for you as well?

On a related side-note, there is an open feature request for parametrizing the writing of inspection link metadata files (see https://github.com/in-toto/in-toto/issues/260).

(cc'ing @SantiagoTorres and @trishankatdatadog)

**Comment by radu-matei** [comment]
I guess that's reasonable - in any case, [this branch](https://github.com/in-toto/in-toto-golang/compare/master...radu-matei:inspections-dir) has the changes required to change the directory, if anyone else needs it in the future.
 
For my use case I ended up directly using a container to perform verifications - see https://github.com/engineerd/in-toto-container.

We can safely close this, thanks!

**Comment by SantiagoTorres** [comment]
Reopening this, it seems that this may be a desirable feature for a couple of folks...

**Comment by adityasaky** [comment]
Closed by #105.
