### ISSUE TITLE
canonical_json encoder coerces floats to ints

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto-golang#49]
**Description of issue or feature request**:
It appears that our implementation of canonical_json is failing the spec, as it coerces float types to ints. The error was nailed down to [this line](https://github.com/in-toto/in-toto-golang/blob/master/in_toto/canonicaljson.go#L53-L59) by @radu-matei 

**Current behavior**:
The input object

```json
{
    "anumber": 1.2,
    "znumber": 2.3
}
```

outputs
`{"anumber":1,"znumber":2}`

**Expected behavior**:
The routine should fail, as do the rust and python implementations. Do, see this [snippet](https://bpaste.net/show/PXJJM)

**Comment by lukpueh** [comment]
Thanks, @radu-matei and @SantiagoTorres for pitching this issue. #50 should fix it.

**Comment by shibumi** [comment]
@SantiagoTorres I think we can close this one.

**Comment by lukpueh** [comment]
Fixed in #50
