### ISSUE TITLE
Moving to Github Actions for CI

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto-golang#62]
*Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.*

**Description of issue or feature request**:
Today I ran into a network problem with appveyor:
```
Build started
git clone -q https://github.com/in-toto/in-toto-golang.git c:\gopath\src\github.com\in-toto\in-toto-golang
fatal: unable to access 'https://github.com/in-toto/in-toto-golang.git/': Failed to connect to github.com port 443: Timed out
Command exited with code 128
```

Mistakes happen. This issue is not intended as a rant about appveyor, but I have read that the TUF team thinks about moving to Github Actions.  Maybe it makes sense for us to switch, too. See this issue as a discussion, if we should move and if so, which benefits we would gain

**Comment by lukpueh** [comment]
We also considered using Travis for windows builds too a few months ago (see https://github.com/theupdateframework/tuf/issues/940#issuecomment-583320212).

Looking into GitHub Actions seems like a good idea though.
