### ISSUE TITLE
ecdsa curve sanity checks

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto-golang#65]
**Description of issue or feature request**:
The current ecdsa implementation does not do sanity checks for different ecdsa curves. Right now, we trust the developer, that
the dev will pick the right curve name in the `key.Scheme` string. Theoretically and practically the dev could just load an ecdsa key with another curve, than specified in the scheme.

**Current behavior**:
We do no sanity checks for ecdsa curves, thus it's possible that ecdsa key and `key.Scheme` do not match.

**Expected behavior**:
We should validate if the curve used in the ecdsa key matches the curve specified in the `key.Scheme` variable.

**Comment by lukpueh** [comment]
Kindly fixed by @shibumi in #78
