### ISSUE TITLE
subsetCheck function as part of our Set implementation

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto-golang#66]
*Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.*

**Description of issue or feature request**:
Right now the SubsetCheck function operates on string slices. It might makes sense to use Sets in our constant getter functions.

**Current behavior**:
constant getter functions return string slices + subsetCheck operates on string slices.

**Expected behavior**:
constant getter functions and subsetcheck function should operate on our Set implementation.

**Comment by shibumi** [comment]
@lukpueh This can be closed now :)

**Comment by lukpueh** [comment]
Closed by #73
