### ISSUE TITLE
ecdsa-sha2-nistp384 support

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto-golang#67]
**Description of issue or feature request**:
The securesystemslib supports `ecdsa-sha2-nistp384` as scheme. We should catch up with the securesystemslib and provide
support for this curve as well. I suggest to use Go's Hash interface for setting the correct hash algorithm: https://godoc.org/crypto#Hash

This could be also useful if we want to support more RSA schemes.

**Current behavior**:
Right now we only support `ecdsa-sha2-nistp256`.

**Expected behavior**:
We should catch up with the securesystemslib and support `ecdsa-sha2-nistp384`, too.

**Comment by shibumi** [comment]
A similar issue I have spotted is this one here:
https://github.com/in-toto/in-toto-golang/issues/31

**Comment by lukpueh** [comment]
Kindly fixed by @shibumi in #78
