### ISSUE TITLE
In-toto record functionality

### ISSUE THREAD

**Issue by shibumi** [in-toto/in-toto-golang#69]
*Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.*

**Description of issue or feature request**:
Most of the run functionality has been fulfilled by #56, what is missing is record functionality for in-toto.
Record functionality is explained here: https://github.com/in-toto/in-toto#in-toto-record
> in-toto-record works similar to in-toto-run but can be used for multi-part software supply chain steps, i.e. steps that are not carried out by a single command. Use in-toto-record start ... to create a preliminary link file that only records the materials, then run the commands of that step or edit files manually and finally use in-toto-record stop ... to record the products and generate the actual link metadata file. For a detailed list of all command line arguments and their usage, run in-toto-record start --help or in-toto-record stop --help, or look at the online documentation.

The difference to the python implementation is, that we do not want a cli for in-toto-golang. The functionality should be implemented as library with  `RecordStart` and `RecordStop` methods.

**Current behavior**:
No record functionality

**Expected behavior**:
In-toto-golang should support record functionality for satisfying the in-toto specification.

**Comment by mikhailswift** [comment]
This is implemented with #119

**Comment by adityasaky** [comment]
Thanks for your work, @mikhailswift!
