### ISSUE TITLE
`go.mod` still not set up correctly

### ISSUE THREAD

**Issue by 06kellyjac** [in-toto/in-toto-golang#83]
**Description of issue or feature request**:

#82 went some way to fix this but it's still not resolved

https://pkg.go.dev/github.com/in-toto/in-toto-golang

![image](https://user-images.githubusercontent.com/9866621/102817497-cb1a8d80-43c7-11eb-8648-2b6f2051bcae.png)

https://pkg.go.dev/github.com/in-toto/in-toto-golang?tab=versions

* `v0.0.0-20201117215500-f3f615b900aa – Nov 17, 2020`
* `v0.0.0-20201013095058-5fba7c22a062 – Oct 13, 2020`
* `v0.0.0-20201006140941-6357e55ad7df – Oct 6, 2020`
* ...etc

**Comment by lukpueh** [comment]
Thanks for submitting this issue, @06kellyjac! Would you mind adding some more info? Is this about an incorrect `go.mod` (issue title), or about the lack of a tagged and/or stable version (screenshot)?

**Comment by 06kellyjac** [comment]
My go to is to blame `go.mod` because it's caused me numerous headaches in the past but yeah it just looks like no tagged versions just yet, I'll close this.
Any idea on when a v0.0.1 will be tagged? SemVer allows for breaking changes within a v0

**Comment by lukpueh** [comment]
> Any idea on when a v0.0.1 will be tagged? SemVer allows for breaking changes within a v0

Good question. I think there's no reason to not just tag v0.1.0. @shibumi, would you like to do the honors?  I even think there's not much missing for a stable major release. cc @SantiagoTorres

**Comment by shibumi** [comment]
Hi everybody,

I spoke already with @SantiagoTorres  a few weeks/months ago and we plan to schedule a Version for it. We should also address the invalid package name. The latter may be important, because I have heard that Go will be more strict about package names in the future (Go 1.16).
