### ISSUE TITLE
Add code documentation

### ISSUE THREAD

**Issue by lukpueh** [in-toto/in-toto-golang#9]
We do not have a lab guideline for go code. It might make sense to
- review existing go code guidelines,
- consider [godoc](https://blog.golang.org/godoc-documenting-go-code) tooling compliance,
- stay close to our [Python guidelines](https://github.com/secure-systems-lab/code-style-guidelines).

**Comment by agamdua** [comment]
Would you be open to using `gofmt` to bring the code formatting in line with the official guidelines? Happy to send a pull request for this.

Best to do it while the project is still small.

**Comment by lukpueh** [comment]
I agree, if we decide to use gofmt, we'd best do it now while the project is small. I did play with the thought but the only difference it makes is that it indents with tabs and aligns assignment parameters and inline comments with additional whitespace. Both things are discouraged by our (Python) guidelines, which may be an okay tradeoff in order to comply with the "universal" go format.

Any thoughts @JustinCappos, @SantiagoTorres, @awwad? It plays into the same discussion as #5, i.e. "do it the go way" vs. "do it as we no-gophers think it's best" :)

**Comment by JustinCappos** [comment]
gofmt seems quite standard.  We should use what makes sense in the go space.

**Comment by lukpueh** [comment]
Okay, sounds good. Let's have #13 reviewed and merged and then make a separate `gofmt` PR.
